// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Group struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	AdminID   int    `json:"adminId"`
}

type GroupConversation struct {
	ID        int    `json:"id"`
	GroupID   int    `json:"groupId"`
	SenderID  int    `json:"senderId"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type GroupMember struct {
	GroupID  int `json:"groupId"`
	MemberID int `json:"memberId"`
}

type Mutation struct {
}

type NewGroup struct {
	Name    string `json:"name"`
	AdminID int    `json:"adminId"`
}

type NewPersonalConversation struct {
	ReceiverName string `json:"receiverName"`
	Content      string `json:"content"`
}

type NewReview struct {
	VideoID     string `json:"videoId"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Rating      int    `json:"rating"`
	UserID      string `json:"userId"`
}

type NewScreenshot struct {
	VideoID     string  `json:"videoId"`
	URL         string  `json:"url"`
	Description *string `json:"description,omitempty"`
}

type NewVideo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	UserID      string `json:"userId"`
	URL         string `json:"url"`
}

type PersonalConversation struct {
	ID         int    `json:"id"`
	SenderID   int    `json:"senderId"`
	ReceiverID int    `json:"receiverId"`
	Content    string `json:"content"`
	CreatedAt  string `json:"createdAt"`
}

type Query struct {
}

type Review struct {
	ID          string `json:"id"`
	VideoID     string `json:"videoId"`
	User        *User  `json:"user"`
	Description string `json:"description"`
	Rating      int    `json:"rating"`
	CreatedAt   string `json:"createdAt"`
}

type Screenshot struct {
	ID      string `json:"id"`
	VideoID string `json:"videoId"`
	URL     string `json:"url"`
}

type Subscription struct {
}

type User struct {
	ID        int     `json:"id"`
	Fullname  string  `json:"fullname"`
	Email     string  `json:"email"`
	IPAddress string  `json:"ipAddress"`
	Gender    *string `json:"gender,omitempty"`
}

type Video struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	User        *User         `json:"user"`
	URL         string        `json:"url"`
	CreatedAt   string        `json:"createdAt"`
	Screenshots []*Screenshot `json:"screenshots,omitempty"`
	Related     []*Video      `json:"related"`
}
